//! Latency histogram with the bucket layout used by the C engine.
//!
//! The Dynomite reference uses a 94-bucket histogram whose offsets are
//! generated by `bucket_offsets[0] = 1` and
//! `bucket_offsets[i] = max(floor(bucket_offsets[i-1] * 1.2),
//! bucket_offsets[i-1] + 1)`. Every operation reproduces the layout
//! and search behaviour of that table: the binary search in
//! [`Histogram::add`] is the same one the reference uses, and
//! [`Histogram::compute`] derives the mean and the 95th, 99th, and
//! 99.9th percentiles.

use std::sync::OnceLock;

/// Number of buckets in the histogram. Mirrors `BUCKET_SIZE`.
pub const BUCKET_SIZE: usize = 94;

fn bucket_offsets() -> &'static [u64; BUCKET_SIZE] {
    static OFFSETS: OnceLock<[u64; BUCKET_SIZE]> = OnceLock::new();
    OFFSETS.get_or_init(|| {
        let mut offsets = [0u64; BUCKET_SIZE];
        let mut last = 1u64;
        offsets[0] = last;
        for slot in offsets.iter_mut().skip(1) {
            let mut next = u64_from_f64_floor(u64_to_f64(last) * 1.2_f64);
            if next == last {
                next += 1;
            }
            *slot = next;
            last = next;
        }
        offsets
    })
}

#[allow(clippy::cast_precision_loss)]
fn u64_to_f64(v: u64) -> f64 {
    v as f64
}

#[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
fn u64_from_f64_floor(v: f64) -> u64 {
    v.floor() as u64
}

#[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
fn u64_from_f64_ceil(v: f64) -> u64 {
    v.ceil() as u64
}

/// Snapshot of the four percentile-related summary metrics.
#[derive(Debug, Default, Clone, Copy, Eq, PartialEq)]
pub struct HistogramSummary {
    /// Arithmetic mean over every observed sample.
    pub mean: u64,
    /// 95th-percentile bucket offset.
    pub val_95th: u64,
    /// 99th-percentile bucket offset.
    pub val_99th: u64,
    /// 99.9th-percentile bucket offset.
    pub val_p999: u64,
    /// Largest sample seen by [`Histogram::add`].
    pub val_max: u64,
}

/// Latency histogram.
///
/// # Examples
///
/// ```
/// use dynomite::util::histogram::Histogram;
///
/// let mut h = Histogram::new();
/// for v in [1u64, 2, 3, 4, 5, 6, 7, 8, 9, 10] {
///     h.add(v);
/// }
/// let s = h.compute();
/// assert!(s.val_95th >= s.val_99th.min(s.val_95th));
/// assert!(s.val_max >= 10);
/// ```
#[derive(Debug, Clone)]
pub struct Histogram {
    buckets: [u64; BUCKET_SIZE],
    val_max: u64,
}

impl Default for Histogram {
    fn default() -> Self {
        Self::new()
    }
}

impl Histogram {
    /// Construct a fresh histogram with all buckets zeroed.
    pub fn new() -> Self {
        Self {
            buckets: [0u64; BUCKET_SIZE],
            val_max: 0,
        }
    }

    /// Reset every bucket and the running max.
    pub fn reset(&mut self) {
        self.buckets = [0u64; BUCKET_SIZE];
        self.val_max = 0;
    }

    /// Read the count for the given bucket index.
    ///
    /// # Examples
    ///
    /// ```
    /// use dynomite::util::histogram::Histogram;
    /// let mut h = Histogram::new();
    /// h.add(1);
    /// assert_eq!(h.bucket(0), 1);
    /// ```
    pub fn bucket(&self, index: usize) -> u64 {
        self.buckets.get(index).copied().unwrap_or(0)
    }

    /// Copy of every bucket count.
    pub fn buckets(&self) -> [u64; BUCKET_SIZE] {
        self.buckets
    }

    /// Largest sample observed so far.
    pub fn max(&self) -> u64 {
        self.val_max
    }

    /// Total number of samples recorded.
    pub fn count(&self) -> u64 {
        self.buckets.iter().sum()
    }

    /// Insert `val` into the appropriate bucket.
    ///
    /// The search mirrors the C `histo_add` loop exactly: the bucket is
    /// found via a binary search on the global offset table, with the
    /// special case `left + 1 == right` selecting `left`.
    pub fn add(&mut self, val: u64) {
        let offsets = bucket_offsets();
        let mut left: usize = 0;
        let mut right: usize = BUCKET_SIZE - 1;
        let mut index: usize = 0;

        while left < right {
            let middle = left + (right - left) / 2;

            match val.cmp(&offsets[middle]) {
                std::cmp::Ordering::Equal => {
                    index = middle;
                    break;
                }
                std::cmp::Ordering::Less => {
                    right = middle;
                }
                std::cmp::Ordering::Greater => {
                    left = middle;
                }
            }

            if left + 1 == right {
                index = left;
                break;
            }
        }

        if left + 1 == right {
            index = left;
        }

        self.buckets[index] = self.buckets[index].saturating_add(1);

        if val > self.val_max {
            self.val_max = val;
        }
    }

    /// Compute the percentile/mean summary.
    ///
    /// Returns `None` when the last bucket overflowed (matches the
    /// C `histo_compute` early-out behaviour, which logs an error and
    /// leaves the summary fields untouched).
    ///
    /// # Examples
    ///
    /// ```
    /// use dynomite::util::histogram::Histogram;
    /// let mut h = Histogram::new();
    /// for v in 1..=100 { h.add(v); }
    /// let s = h.compute();
    /// assert!(s.mean >= 1);
    /// assert!(s.val_95th >= s.val_p999.min(s.val_95th));
    /// ```
    pub fn compute(&self) -> HistogramSummary {
        self.compute_inner().unwrap_or(HistogramSummary {
            val_max: self.val_max,
            ..HistogramSummary::default()
        })
    }

    fn compute_inner(&self) -> Option<HistogramSummary> {
        let last_bucket = BUCKET_SIZE - 1;
        if self.buckets[last_bucket] > 0 {
            return None;
        }

        let total = u64_to_f64(self.count());
        let p95_count = u64_from_f64_floor(total * 0.95);
        let p99_count = u64_from_f64_floor(total * 0.99);
        let p999_target = u64_from_f64_floor(total * 0.999);

        let offsets = bucket_offsets();

        let mut val_95th = 0u64;
        let mut val_99th = 0u64;
        let mut val_p999 = 0u64;
        let mut elements: u64 = 0;
        let mut sum: u128 = 0;

        for (i, offset) in offsets.iter().take(last_bucket).enumerate() {
            elements += self.buckets[i];
            if elements >= p95_count && val_95th == 0 {
                val_95th = *offset;
            }
            if elements >= p99_count && val_99th == 0 {
                val_99th = *offset;
            }
            if elements >= p999_target && val_p999 == 0 {
                val_p999 = *offset;
            }
            sum += u128::from(self.buckets[i]) * u128::from(*offset);
        }

        let mean = if elements == 0 {
            0
        } else {
            u64_from_f64_ceil(sum_as_f64(sum) / u64_to_f64(elements))
        };

        Some(HistogramSummary {
            mean,
            val_95th,
            val_99th,
            val_p999,
            val_max: self.val_max,
        })
    }

    /// Look up the smallest bucket offset whose cumulative count
    /// reaches `percentile` (a fraction in `[0, 1]`).
    ///
    /// Returns `0` if no samples have been recorded.
    ///
    /// # Examples
    ///
    /// ```
    /// use dynomite::util::histogram::Histogram;
    /// let mut h = Histogram::new();
    /// for v in 1..=100 { h.add(v); }
    /// assert!(h.percentile(0.5) > 0);
    /// ```
    pub fn percentile(&self, percentile: f64) -> u64 {
        if !(0.0..=1.0).contains(&percentile) {
            return 0;
        }
        let last_bucket = BUCKET_SIZE - 1;
        if self.buckets[last_bucket] > 0 {
            return 0;
        }
        let target = u64_from_f64_floor(u64_to_f64(self.count()) * percentile);
        if target == 0 {
            return 0;
        }
        let offsets = bucket_offsets();
        let mut elements: u64 = 0;
        for (i, offset) in offsets.iter().take(last_bucket).enumerate() {
            elements += self.buckets[i];
            if elements >= target {
                return *offset;
            }
        }
        0
    }
}

#[allow(clippy::cast_precision_loss)]
fn sum_as_f64(v: u128) -> f64 {
    v as f64
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bucket_offsets_strictly_increase() {
        let offs = bucket_offsets();
        for w in offs.windows(2) {
            assert!(w[1] > w[0], "bucket offsets must increase: {w:?}");
        }
        assert_eq!(offs[0], 1);
    }

    #[test]
    fn first_few_buckets_match_c_layout() {
        // Replay the C loop:
        //   last = 1; offsets[0] = 1
        //   for i in 1..N: next = floor(last * 1.2);
        //                  if next == last { next += 1 }
        //                  offsets[i] = next; last = next
        // The first nineteen entries land at:
        let want = [
            1u64, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 14, 16, 19, 22, 26, 31, 37, 44,
        ];
        for (i, expected) in want.iter().enumerate() {
            assert_eq!(bucket_offsets()[i], *expected, "offset[{i}]");
        }
    }

    #[test]
    fn add_increments_correct_bucket() {
        let mut h = Histogram::new();
        h.add(1);
        assert_eq!(h.bucket(0), 1);
        h.add(2);
        assert_eq!(h.bucket(1), 1);
        h.add(3);
        assert_eq!(h.bucket(2), 1);
        assert_eq!(h.count(), 3);
        assert_eq!(h.max(), 3);
    }

    #[test]
    fn percentile_is_monotone_non_decreasing() {
        let mut h = Histogram::new();
        for v in 1..=200u64 {
            h.add(v);
        }
        let mut prev = 0u64;
        let probes = [0.0, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99, 0.999, 1.0];
        for p in probes {
            let cur = h.percentile(p);
            assert!(cur >= prev, "p={p} cur={cur} prev={prev}");
            prev = cur;
        }
    }

    #[test]
    fn compute_rejects_overflow() {
        let mut h = Histogram::new();
        // Force the last bucket directly so we exercise the overflow guard.
        h.buckets[BUCKET_SIZE - 1] = 5;
        let s = h.compute();
        assert_eq!(s.mean, 0);
        assert_eq!(s.val_95th, 0);
        assert_eq!(s.val_99th, 0);
        assert_eq!(s.val_p999, 0);
    }
}
