/* config.h - autoconf-style configuration for the vendored TRE
   build. This file is what TRE's lib/*.c sources include via
   `#ifdef HAVE_CONFIG_H #include <config.h>`. It supplies the
   HAVE_* and TRE_* macros that are normally generated by
   `./configure` from configure.ac.

   The settings here mirror the byte-only build described in
   tre-config.h: approximate matching on, wide-char and multibyte
   off, no system regex.h.

   Add new HAVE_* defines here when porting tre-sys to a host
   that lacks them; the goal is a `cc::Build::compile` invocation
   that does not need any host-specific feature probing.
*/

#ifndef TRE_SYS_CONFIG_H
#define TRE_SYS_CONFIG_H 1

/* Standard headers TRE expects on any modern POSIX host. */
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1

/* Character classification helpers we want exposed. */
#define HAVE_ISASCII 1
#define HAVE_ISBLANK 1

/* Multibyte primitives are not used because TRE_MULTIBYTE is
   undefined; leave them undefined too so TRE's #ifdef gates
   stay quiet. */
/* #undef HAVE_MBSTATE_T */
/* #undef HAVE_MBRTOWC */

/* Disable <alloca.h> path; xmalloc is fine for our scale. */
/* #undef HAVE_ALLOCA */
/* #undef HAVE_ALLOCA_H */
/* #undef TRE_USE_ALLOCA */

/* The TRE regex_t struct stores the compiled TNFA in `value`.
   Both regcomp.c and regexec.c use the macro TRE_REGEX_T_FIELD
   to get at it. */
#define TRE_REGEX_T_FIELD value

/* Approximate matching is the whole point of binding TRE. */
#define TRE_APPROX 1

/* Wide-character / multibyte off; raw byte mode only. */
/* #undef TRE_WCHAR */
/* #undef TRE_MULTIBYTE */
/* #undef HAVE_WCHAR_H */
/* #undef HAVE_WCTYPE_H */

/* No system regex.h. */
/* #undef TRE_USE_SYSTEM_REGEX_H */

/* Disable assertions in production builds. */
#define NDEBUG 1

/* Package metadata (used only by debug prints; pinned to the
   submodule tag). */
#define PACKAGE "tre"
#define PACKAGE_NAME "TRE"
#define PACKAGE_VERSION "0.8.0"
#define PACKAGE_STRING "TRE 0.8.0"
#define VERSION "0.8.0"

#define TRE_VERSION "0.8.0"
#define TRE_VERSION_1 0
#define TRE_VERSION_2 8
#define TRE_VERSION_3 0

#endif /* TRE_SYS_CONFIG_H */
