/* tre-config.h - TRE configuration header for the vendored build.

   Generated by hand to replace the autoconf-driven
   tre-config.h.in shipped with TRE 0.8.0. The settings below
   match what an `./configure --disable-wchar --disable-multibyte
   --enable-approx --enable-system-abi=no` invocation would
   produce on a modern GNU/Linux host:

   * Approximate matching is on (TRE_APPROX). This is the whole
     reason we bind libtre.
   * Wide-character and multibyte handling are off. The dyntext
     index works on raw byte slices, so we want STR_BYTE in the
     matcher and tre_char_t = unsigned char throughout. Disabling
     these features also keeps the C side free of locale, mbstate,
     and wchar dependencies.
   * The system regex.h is NOT pulled in; we keep TRE's own
     regex_t / regmatch_t / reg_errcode_t types and re-export them
     from src/lib.rs. This avoids glibc's __regexec ABI variants
     leaking into the FFI layer.
*/

/* libutf8 is a third-party UTF-8 wctype shim; we do not use it. */
/* #undef HAVE_LIBUTF8_H */

/* The system reg_errcode_t typedef (only relevant when reusing
   the system regex.h, which we do not). */
/* #undef HAVE_REG_ERRCODE_T */

#define HAVE_SYS_TYPES_H 1

/* No <wchar.h> needed when TRE_WCHAR is off. */
/* #undef HAVE_WCHAR_H */

#define TRE_APPROX 1

/* Multibyte off: TRE_MB_CUR_MAX collapses to 1 and the matcher
   selects STR_BYTE for tre_reganexec. */
/* #undef TRE_MULTIBYTE */

/* Wide-character mode off: tre_char_t is `unsigned char`. */
/* #undef TRE_WCHAR */

/* Tell TRE not to pull in the host regex.h. */
/* #undef TRE_USE_SYSTEM_REGEX_H */
/* #undef TRE_SYSTEM_REGEX_H_PATH */

/* TRE 0.8.0 release. */
#define TRE_VERSION "0.8.0"
#define TRE_VERSION_1 0
#define TRE_VERSION_2 8
#define TRE_VERSION_3 0
